### ISSUE TITLE
Map section remains grey with no content

### ISSUE THREAD

**Issue by csaeum** [cowegis/cowegis-contao-bundle#4]
I've already asked in the forum but haven't had an answer yet.
I've now managed to get it to at least show me the section of the map, i.e. the area where it should appear on the page.
But it remains empty. So I think the right layers are missing. When I try to assign them to the map, the following error occurs:

> Netzmacht\Contao\Toolkit\Callback\Invoker::invoke(): Argument #1 ($callback) must be of type callable, array given, called in /data/web/1/000/162/643/607096/htdocs/Contao-CMS/53-LTS/vendor/cowegis/cowegis-contao-bundle/src/EventListener/Dca/MapLayerSelectionDcaListener.php on line 110

Mein Contao  Version 5.3.15
PHP 8.3
Plugin: cowegis/cowegis-contao-bundle: Version 1.0.0
& 
cowegis/cowegis-contao-provider-layer-bundle: Version 1.0.0

**Comment by dmolineus** [comment]
Meawhile fixed with netzmacht/contao-toolkit 4.0.2
